
exam: sequence3.o seq_ex3.o node1.o
	g++ seq_ex3.o sequence3.o node1.o -o exam

sequence3.o: sequence3.cxx
	g++ -Wall -c sequence3.cxx

seq_ex3.o: seq_ex3.cxx
	g++ -Wall -c seq_ex3.cxx

node1.o: node1.cxx
	g++ -Wall -c node1.cxx
